In [2]:
import numpy as n

In [3]:
a = n.array([1,2,3,4,5])
a += 2
a

array([3, 4, 5, 6, 7])

In [4]:
a *= 3
a

array([ 9, 12, 15, 18, 21])

In [5]:
a //= 2
a

array([ 4,  6,  7,  9, 10])

In [6]:
arr = n.array([1,2,3,6,4,5])
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [4]:
x = n.array([1,2,3,4,5,1,2,1,1,1])
print("Mode of x: ",n.bincount(x).argmax())

Mode of x:  1


In [6]:
print("Maximum frequency of mode of array: ",n.bincount(x).max())

Maximum frequency of mode of array:  5


In [11]:
y=n.array([1,1,1,2,3,4,2,4,3,3,])
b=n.bincount(y)
maximum=max(b)
print("Mode of y: ",end="")
for i in range(len(b)):
    if b[i]==maximum:
        print(i,end=" ")
print()
print("Maximum frequency of mode of array: ",n.bincount(y).max())

Mode of y: 1 3 
Maximum frequency of mode of array:  3


In [13]:
arr=n.array([[10,20,30],[40,50,60],[70,80,90]])
print("Element at first row second column: ",arr[0,1])
print("Element at third row first column: ",arr[2,0])

Element at first row second column:  20
Element at third row first column:  70


In [ ]:
Yash = n.linspace(10,100,25)
print("Original Array: ",Yash)
print("Dimension of array: ",Yash.ndim)
print("Shape of array: ",Yash.shape)
print("Total no. of elements of Array",Yash.size)
print("Datatype of array: ",Yash.dtype)
print("Size of array(Bytes): ",Yash.itemsize*Yash.size)
print("Transpose of array using reshape: ",Yash.reshape(Yash.size,1))
print("Transpose using attribute T: ",Yash.T)

Original Array:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimension of array:  1
Shape of array:  (25,)
Total no. of elements of Array 25
Datatype of array:  float64
Size of array(Bytes):  200
Transpose of array using reshape:  [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using attribute T:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [ ]:
UCS420_Yash = n.array([10,20,30,40,50,60,70,80,90,15,20,35]).reshape(3,4)
print("Original array: ",UCS420_Yash)
print("Mean of array: ",n.mean(UCS420_Yash))
print("Median of array: ",n.median(UCS420_Yash))
print("Max of array: ",n.max(UCS420_Yash))
print("Min of array: ",n.min(UCS420_Yash))
print("Unique of elements of array: ",n.unique(UCS420_Yash))
Reshaped_UCS420_Yash=UCS420_Yash.reshape(4,3)
print("Reshaped array(4,3): ",Reshaped_UCS420_Yash)
Resized_UCS420_Yash=n.resize(UCS420_Yash,(2,3))
print("Resized array(2,3): ",Resized_UCS420_Yash)

Original array:  [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean of array:  43.333333333333336
Median of array:  37.5
Max of array:  90
Min of array:  10
Unique of elements of array:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array(4,3):  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array(2,3):  [[10 20 30]
 [40 50 60]]
